pages/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import HomePageView, CadastroView, TelaUsuarioView, CadastrarEmpresaView, CadastrarProfissionalView, CadastrarPessoaView, OferecerServicoView, AcompanharServicoView, DetalheServicoView, HistoricoServicoView
from django.conf.urls import include
from django.contrib.auth import authenticate, login

app_name = "pages"

urlpatterns = [
    path("", HomePageView.as_view(), name="TelaInicial"),
    path("cadastro", CadastroView.as_view() , name="cadastro"),    
    path("pessoa", CadastrarPessoaView.as_view(), name="tela_cadastrar_pessoa"),
    path("empresa", CadastrarEmpresaView.as_view(), name="tela_cadastrar_empresa"),
    path("profissional", CadastrarProfissionalView.as_view(), name="tela_cadastrar_profissional"),
    path("perfil", TelaUsuarioView.as_view(), name="tela_usuario"),
    path('login', login, {'template_name': 'tela_login.html'}, name='login'),
    path('', include('django.contrib.auth.urls')),
    path('oferecer_servico', OferecerServicoView.as_view(), name='oferecer_servico'),
    path('acompanhar_servico', AcompanharServicoView.as_view(), name='acompanhar_servico'),
    # path('finalizaRegister', finalizeRegister, name='finalizaRegister'),
    path('detalhe_servico', DetalheServicoView.as_view(), name='detalhe_servico'),
    path('historico_servico', HistoricoServicoView.as_view(), name='historico_servico'),
]

sd/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pages.urls", namespace="pages")),

]

pages/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

TIPO_USUARIO = (
    ("pessoa", "Pessoa"),
    ("profissional", "Profissional"),
    ("empresa", "Empresa")
)

ESTADOS = (
    ("BA", "Bahia"),
    ("PE", "Pernambuco")
)

class Usuario(AbstractUser):
    telefone = models.CharField(max_length=16)
    tipo_usuario = models.CharField(max_length=12,choices=TIPO_USUARIO)

class Endereco(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, blank=True, null=True, related_query_name="usuario")
    cidade = models.CharField(max_length=255)  
    estado = models.CharField(max_length=2,choices=ESTADOS)  

class Empresa(models.Model):
    usuario = models.OneToOneField("Usuario", on_delete=models.CASCADE)
    cnpj = models.IntegerField(primary_key=True)

    def __str__(self):
        return str(self.cnpj)

class Pessoa(models.Model):
    usuario = models.OneToOneField("Usuario", on_delete=models.CASCADE)
    cpf = models.IntegerField(primary_key=True)

    def __str__(self):
        return str(self.cpf)
    

class Profissional(models.Model):
    pessoa = models.OneToOneField("Pessoa", on_delete=models.CASCADE)

    def __str__(self):
        return  str(f'{self.pessoa.nome} | {self.pessoa.cpf}')

class Servico(models.Model):
    PERIODO_CHOICES = (
        ("Hora", "Pagamento por hora"),
        ("Dia", "Pagamento por dia")
    )

    profissional = models.ManyToManyField("Profissional")
    area = models.CharField("Área do serviço", max_length=255)
    valorDiaria = models.FloatField(null=True)
    valorHora = models.FloatField(null=True)
    periodo = models.CharField(max_length=4, choices=PERIODO_CHOICES, blank=False, null=False)

# class ProXServ(models.Model):
#     prof_pk = models.ForeignKey(Profissional)
#     serv_pk = models.ForeignKey(Servico)
#     experiencia = models.IntegerField()
#     avaliacao = models.IntegerField()

class ContratoPessXProf(models.Model):
    prof_pk = models.ForeignKey("Profissional", on_delete=models.CASCADE)
    pessoa_pk = models.ForeignKey("Pessoa", on_delete=models.CASCADE)
    data = models.DateField(auto_now=True)
    duracaoHora = models.IntegerField()

class EmpXServ(models.Model):
    empresa_pk = models.ForeignKey("Empresa", on_delete=models.CASCADE)
    serv_pk = models.ForeignKey("Servico", on_delete=models.SET_NULL, null=True)
    experiencia = models.IntegerField()
    avaliacao = models.IntegerField()

class ContratoEmpXPess(models.Model):
    pessoa_pk = models.ForeignKey("Pessoa", on_delete=models.CASCADE)
    empresa_pk = models.ForeignKey("Empresa", on_delete=models.CASCADE)
    data = models.DateField(auto_now=True)
    duracaoHora = models.IntegerField()

class ContratoEmpXProf(models.Model):
    profissional_pk = models.ForeignKey("Profissional", on_delete=models.CASCADE)
    empresa_pk = models.ForeignKey("Empresa", on_delete=models.CASCADE)
    data = models.DateField(auto_now=True)
    duracaoHora = models.IntegerField()

pages/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django import forms
from crispy_forms.helper import FormHelper

class UserAdminCreationForm(UserCreationForm):
    class Meta:
        model = Usuario
        fields = ['username','email']

class UserAdminForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['username','email','is_active','is_staff']

class Cadastro(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    def __init__(self, *args, **kwargs):
        super(Cadastro, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)

        for fieldname in ['password1', ]:
            self.fields[fieldname].help_text = None
        
        for fieldname in ['password2', ]:
            self.fields[fieldname].help_text = None

        for fieldname in ['username', ]:
            self.fields[fieldname].help_text = None

        for key in self.fields:
            self.fields[key].required = True

        self.helper.form_show_errors = False

    class Meta:
        model = Usuario
        fields = ('tipo_usuario', 'username', 'password1', 'password2', 'email', 'telefone',)


# class Cadastro(forms.Form):
#     nome = forms.CharField()
#     email = forms.EmailField(required=True)#require True para que seja obrigado receber o email
#     senha = forms.CharField(widget=forms.PasswordInput())
#     confirmar_senha = forms.CharField(widget=forms.PasswordInput())
#     telefone = forms.CharField(max_length=12)
#     cpf = forms.CharField()
#     cnpj = forms.IntegerField()
#     cidade = forms.CharField()
#     estado = forms.ChoiceField(choices=ESTADOS)

pages/views.py
from django.views.generic import TemplateView, FormView, DetailView
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from .forms import Cadastro
from .models import Usuario, Endereco

# def finalizeRegister(request):
#     if not(Endereco.objects.filter(usuario__id=request.user.id)):
#         return redirect('pages:tela_cadastrar_' + request.user.tipo_usuario)
#     return redirect('pages:TelaInicial')

class HomePageView(TemplateView):
    template_name = "TelaInicial.html"

class CadastroView(FormView):
    template_name = "tela_cadastro.html"
    form_class = Cadastro

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('pages:login') 

class TelaUsuarioView(TemplateView):
    template_name = "Tela_usuario.html"
           
class CadastrarPessoaView(TemplateView):
    template_name = "tela_cadastrar_pessoa.html"

class CadastrarEmpresaView(TemplateView):
    template_name = "tela_cadastrar_empresa.html"
    
class CadastrarProfissionalView(TemplateView):
    template_name = "tela_cadastrar_profissional.html"

class DetalheServicoView(TemplateView):
    template_name = 'detalheServico.html'

class OferecerServicoView(TemplateView):
    template_name = 'ofertadeServico.html'

class AcompanharServicoView(TemplateView):
    template_name = 'acompanharServico.html'
    
class HistoricoServicoView(TemplateView):
    template_name = 'tela_historico_servico.html'

templates/TelaInicial.html
{% extends 'base.html' %}

{% block title %}Tela Inicial{% endblock %}

{% block content %}

<!-- <div id="tela-inicial" class="container-fluid vh-100">

    <div class="container d-flex align-items-center">
        <div class="filtro-servico col-6">
            qwe
        </div>
    </div>
    
</div> -->

        <!--SLIDER-->
        <div id="slider" class="container-fluid vh-100 t-5 pt-5">
            
            <div id="filtro-servico" class="container col-6 py-3">
                
                <h1 class="title text-center mb-5 h1">Encontre o serviço desejado!</h1>

                    <form>
                        <div class="row">
                            <div class="col">
                                <input type="text" class="form-control" placeholder="Serviço">
                            </div>
                            <div class="col">
                                <input type="text" class="form-control" placeholder="Cidade">
                            </div>
                        </div>
                    </form>

                    <div class="row my-3">

                        <div class="col">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1"
                                    value="option1">
                                <label class="form-check-label" for="inlineRadio1">
                                    Pessoa
                                </label>
                            </div>
                        </div>

                        <div class="col">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2"
                                    value="option2">
                                <label class="form-check-label" for="inlineRadio2">
                                    Empresa
                                </label>
                            </div>
                        </div>
    
                    </div>
                   
                    <div id="botaopesquisar" class="mx-auto mt-5">
    

                        <button type="button" class="btn btn-light" >
                            Pesquisar
                        </button>
                    </div>

            </div>
        
           
           
            <div id="list-services" class="mt-5 mx-auto">
    
                <table class="table table-hover">
                    <thead>
                      <tr>
                        <th scope="col">Profissional</th>
                        <th scope="col">Serviço</th>
                        <th scope="col">Experiência</th>
                        <th scope="col">Avaliação</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <th scope="row">1</th>
                        <td>Mark</td>
                        <td>Otto</td>
                        <td>@mdo</td>
                      </tr>
                      <tr>
                        <th scope="row">2</th>
                        <td>Jacob</td>
                        <td>Thornton</td>
                        <td>@fat</td>
                      </tr>
                    </tbody>
    
                  </table>
    
            </div>
    
        </div>
        
        <!--//SLIDER-->        
    
{% endblock %}

templates/acompanharServico.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Acompanhar Serviço{% endblock %}
{% load static %}
{% block content %}

    <div id="acompanhar-servico" class="container-fluid vh-100">

            <div class="container " >
            <div>
                <p id="texto-servico-em-andamento">Serviços em Andamento</p>
            </div>
            <div  class="overflow-hidden">
                <div id="card-acomp" class=" h-50 w-75 mt-2 ">
                    <div class="row">
                        <div class="col">
                            <p id="texto-acomp">Pessoa ou empresa</p>
                            <p id="texto-acomp">Serviço</p>
                            <p id="texto-acomp">Data</p>
                            <p id="texto-acomp">Avaliação</p>
                        </div>
                        <div class="col-md-3 ms-md-auto mt-5">
                            <button type="button" class="botao" >
                                Finalizar
                            </button>   
                        </div>
                    </div> 
                </div>
                <div id="card-acomp" class="h-50 w-75 mt-2">
                    <div class="row" >
                        <div class="col">
                            <p id="texto-acomp">Pessoa ou empresa</p>
                            <p id="texto-acomp">Serviço</p>
                            <p id="texto-acomp">Data</p>
                            <p id="texto-acomp">Avaliação</p>
                        </div>
                        <div class="col-md-3 ms-md-auto mt-5">
                            <button type="button" class="botao"  >
                                Finalizar
                            </button>   
                        </div>
                    </div> 
                </div>
                <div id="card-acomp" class="h-50 w-75 mt-2">
                    <div class="row">
                        <div class="col">
                            <p id="texto-acomp">Pessoa ou empresa</p>
                            <p id="texto-acomp">Serviço</p>
                            <p id="texto-acomp">Data</p>
                            <p id="texto-acomp">Avaliação</p>
                        </div>
                        <div class="col-md-3 ms-md-auto mt-5">
                            <button type="button" class="botao" >
                                Finalizar
                            </button>   
                        </div>
                    </div> 
                </div>
                <div id="card-acomp" class="h-50 w-75 mt-2">
                    <div class="row">
                        <div class="col">
                            <p id="texto-acomp">Pessoa ou empresa</p>
                            <p id="texto-acomp">Serviço</p>
                            <p id="texto-acomp">Data</p>
                            <p id="texto-acomp">Avaliação</p>
                        </div>
                        <div class="col-md-3 ms-md-auto mt-5">
                            <button type="button" class="botao" >
                                Finalizar
                            </button>   
                        </div>
                    </div> 
                </div>
            </div>
            
        </div>

    </div>


{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Biblioteca de fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,900;1,700&display=swap"
        rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Sanchez&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/main.css' %}"> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
        crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div id="header">
        <div class="container-fluid px-5">

            <nav class="navbar navbar-expand-md navbar-light justify-content-between">

                <a class="navbar-brand" href="{% url 'pages:TelaInicial' %}">
                    <img src="{%static 'assets/logo.png'%}" class="img-fluid" />
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">

                    <span class="navbar-toggler-icon"></span>

                </button>

                <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNav">

                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'pages:TelaInicial' %}">Página Inicial</a>
                        </li>
                        
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'pages:tela_usuario' %}">Perfil</a>
                            
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'pages:logout' %}">Sair</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'pages:login' %}">Entrar</a>
                        </li>
                        {% endif %}

                    </ul>
                </div>
            </nav>
        </div>
    </div>
    <main>
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" 
    crossorigin="anonymous"></script>
</body>
</html>

templates/detalheServico.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Detalhes do Serviço{% endblock %}
{% load static %}
{% block content %}
    <div id="detalhe-servico" class="container-fluid vh-100">
        
        <div class="container px-5">
    
            <div class="row  align-items-center">           
         
                <div class="col">
    
                    <div class="mb-2">
                        <span class="text">Kemuel Rocha,</span>
                        <span class="text"> Petrolina-PE</span>
                    </div>
    
                    <div  class="mb-1">
                        <i class="fa fa-phone icon"></i>
                        <span class="numero-contato">XX XXXXX-XXXX</span>
                    </div>
    
                    <div>
                        <i class="fa fa-envelope icon"></i>
                        <span class="numero-contato">exemplo@gmail.com</span>
                    </div>
    
                
                </div>
    
                <div class=" col d-flex justify-content-end">
                    <span class="fa fa-star star-checked"></span>
                    <span class="fa fa-star star-checked"></span>
                    <span class="fa fa-star star-checked"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                </div>
    
            </div>
    
            <div class="row mt-5 er">

                        <div class="col">

                            <div class="mb-2">
                                <label for="exampleInputEmail1" class="form-label">Área do serviço</label>
                                <input readonly value="xxxxxxxxxx" type="text" class="form-control" > 
                            </div>                            

                            <div class="mb-2">
                                <label for="exampleInputEmail1" class="form-label">Experiência (anos)</label>
                                <input readonly value="xxxxxxxxxx" type="text" class="form-control " >
                            </div>                            

                        </div>
    
                        <div class="col">
                            
                            <div class="mb-2">
                                <label for="exampleInputEmail1" class="form-label">Título do Serviço</label>
                                <input readonly value="xxxxxxxxxx" type="text" class="form-control" >
                            </div>      
                            
    
                            <div class="row">

                                <div class="col mb-2">
                                    <label for="exampleInputEmail1" class="form-label">Valor</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon1">R$</span>
                                        <input readonly value="500" type="text" class="form-control" >
                                    </div>
                                    
                                </div>      
                                <div class="col mb-2">
                                    <label for="exampleInputEmail1" class="form-label">Período</label>
                                    <input readonly value="xxxxxxxxxx" type="text" class="form-control" >
                                </div>      
    
                            </div>
    
                        </div>

                        <div class=" mb-2">
                            <label for="exampleInputEmail1" class="form-label">Descrição</label>
                            <textarea  readonly class="form-control" maxlength="10" rows="8">xxxxxxxxxx</textarea>
                        </div>    
                            
                        

            </div>

        </div>
      
    </div>
{% endblock %}

templates/ofertadeServico.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Oferta de Serviço{% endblock %}
{% load static %}
{% block content %}
        <div id="ofertadeServico" class="container-fluid vh-100">
            <div class="container-fluid d-flex justify-content-center mt-5">
                <div class="row justify-content-around">
                    <div class="col">
                        <input type="text" class="form-control mb-4" placeholder="Área do serviço">
                        <input type="text" class="form-control mb-4" placeholder="Experiência(anos)">
                    </div>
                    <div class="col">
                        <input type="text" class="form-control mb-4" placeholder="Título de serviço">
                        <div class="row">
                            <div class="col">
                                <input type="text" class="form-control mb-4" placeholder="Valor em R$">
                            </div>
                            <div class="col">
                                <select class="form-select " aria-label=".form-select-lg example">
                                    <option selected>Diária ou Hora</option>
                                    <option value="1">Por Hora</option>
                                    <option value="2">Diária</option>
                                </select>
                            </div>
                        </div>

                    </div>
                    <div class="form-group">
                        <textarea class="form-control" id="exampleFormControlTextarea1" maxlength="10" rows="12"
                            placeholder="Descrição"></textarea>
                    </div>
                    <div id="botaopadrao" class="mx-auto mt-3 d-flex justify-content-end" >
                        <button type="button" class="botao">
                            Confirmar
                        </button>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/tela_cadastrar_empresa.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Cadastro{% endblock %}

{% block content %}

<div id="login-register-main" class="container-fluid vh-100"> 
    
    <div class="row justify-content-around d-flex align-items-center">

        <div class=" container mt-3 col-7 g-0">
            
            <div class="title-bar d-flex justify-content-center">
                <h3 class="py-2">Cadastro Empresa</h3>
            </div>

            <div class="contentt d-flex flex-column justify-content-center px-4">              
                <form  method='POST'>
                    {%csrf_token%}
                                        
                    <div id="botaopadrao" class="mx-auto mt-3 mb-3">
                        <button type="submit"  class="botao">
                            Cadastrar
                        </button>
                    </div>
                </form>
        
        
            </div>
        </div>
    
    </div>
</div>

{% endblock %}

templates/tela_cadastrar_pessoa.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Cadastro{% endblock %}

{% block content %}

<div id="login-register-main" class="container-fluid vh-100"> 
    
    <div class="row justify-content-around d-flex align-items-center">

        <div class=" container mt-3 col-7 g-0">
            
            <div class="title-bar d-flex justify-content-center">
                <h3 class="py-2">Cadastro Pessoa</h3>
            </div>

            <div class="contentt d-flex flex-column justify-content-center px-4">              
                <form  method='POST'>
                    {%csrf_token%}
                    
                    
                    <div id="botaopadrao" class="mx-auto mt-3 mb-3">
                        <button type="submit"  class="botao">
                            Cadastrar
                        </button>
                    </div>
                </form>
        
        
            </div>
        </div>
    
    </div>
</div>




{% endblock %}

templates/tela_login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Entrar{% endblock %}

{% block content %}

<div id="login-register-main" class="container-fluid vh-100"> 
    <div class="container">

        <div class="row justify-content-around d-flex align-items-center">
    
            <div class="login mt-5 col-5 g-0"> 
    
                <div class="title-bar  d-flex justify-content-center">
                    <h3 class="py-2">Login</h3>
                </div>
    
                <div class="content d-flex flex-column justify-content-center px-4">
                    <p class="my-5 mx-auto">
                        Preencha os campos abaixo e faça o login
                    </p>
    
                    <form method="post" action="">
                        {% csrf_token %}
                        {{form|crispy}}
                       
                        <a href="{% url 'pages:cadastro' %}" >Não sou cadastrado</a>

                        <div id="botaopadrao" class="mx-auto mt-5 mb-5">
                            <button type="submit"  class="botao">
                                Entrar
                            </button>
                        </div>
                    </form>

                    

                </div>

                </div>
            </div>
    
        </div>
    
    </div>
</div>

{% endblock %}

templates/tela_usuario.html
{% extends 'base.html' %}

{% block title %}Tela Inicial{% endblock %}
{% load static %}
{% block content %}
    <div id="tela-usuario" class="container-fluid vh-100">

        <div class="container d-flex flex-column  align-items-center">

            <div>
                <img src="{%static '/assets/person-icon.svg'%}" width="160"   alt="">
            </div>

            <div class="mt-2 mb-1">
                <span class="text">{{ user.username }},</span>
                <span class="text"> Petrolina-PE</span>
            </div>

            <div class="d-flex flex-row">
               <div class="me-4">
                    <i class="fa fa-phone icon"></i>
                    <span class="numero-contato">{{ user.telefone }}</span>
               </div>

               <div>
                    <i class="fa fa-envelope icon"></i>
                    <span class="numero-contato">{{ user.email }}</span>
               </div>

            </div>

            <div class="d-flex flex-row justify-content-center mt-3">

                <div class="d-flex flex-row align-items-center me-5">
                    <div>
                        
                        <img src="{%static '/assets/edit-icon.svg'%}" class="edit-exit-icon me-2"  alt="">
                    </div>
                    <div>
                        <span class="user-option">Editar</span>
                    </div>
                </div> 
           </div>    
        </div>

        <div class="divider-line mt-4 mb-5"></div>

        <div class="d-flex flex-row justify-content-center">

            <a href="{% url 'pages:oferecer_servico' %}" class="ms-5 me-5 mb-5 mt-5">
                <div class="d-flex flex-row align-items-center">
                    <div>
                        <img src="{%static '/assets/plus-icon.svg'%}" class="user-option-icon me-3"  alt="">
                    </div>
                    <div>
                        <span class="user-option">Oferecer<br>Serviço</span>
                    </div>
                </div>
            </a>

            <a href="" class="ms-5 me-5 mb-5 mt-5">
                <div class="d-flex flex-row align-items-center">
                    <div>
                        <img src="{%static '/assets/crosshair-icon.svg'%}" class="user-option-icon me-3"  alt="">
                    </div>
                    <div>
                        <span class="user-option">Contratar<br>Serviço</span>
                    </div>
                </div>
            </a>
  
            <a href="{% url 'pages:acompanhar_servico' %}" class="ms-5 me-5 mb-5 mt-5">
                <div class="d-flex flex-row align-items-center">
                    <div>
                        <img src="{%static '/assets/hourglass-icon.svg'%}" class="user-option-icon me-3"  alt="">
                    </div>
                    <div>
                        <span class="user-option">Serviços em<br>Andamento</span>
                    </div>
                </div>
            </a>

           <a href="{% url 'pages:historico_servico' %}" class="ms-5 me-5 mb-5 mt-5">
                <div class="d-flex flex-row align-items-center">
                    <div>
                        <img src="{%static '/assets/stopwatch-icon.svg'%}" class="user-option-icon me-3"  alt="">
                    </div>
                    <div>
                        <span class="user-option">Histórico de<br>Serviços</span>
                    </div>
                </div>
           </a>
          
            </div>

            <div class="divider-line mt-5"></div>
            
        </div>

    </div>


{% endblock %}